apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: gcr.io/nnyn-dev/ingress-tester:latest
        readinessProbe:
          httpGet:
            port: 8080
            path: "/podreadiness"
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            port: 8080
            path: "/podliveness"
          initialDelaySeconds: 10
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
...
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: app1
  ports:
  - port: 8080
    targetPort: 8080
...
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app1-ingress
spec:
  rules:
  - http:
      paths:
        - path: /*
          backend:
            serviceName: app1-service
            servicePort: 8080
