swagger: "2.0"
info:
  description: "A simple Google Cloud Endpoints API example."
  title: "Endpoints Example"
  version: "1.0.0"
host: "app3.endpoints.nnyn-dev.cloud.goog"
consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "http"
paths:
  "/podreadiness":
    get:
      operationId: "podreadiness"
      responses:
        200:
          description: "Echo"
  "/podliveness":
    get:
      operationId: "podliveness"
      responses:
        200:
          description: "Echo"
